### PR TITLE
Build out

### PR DESCRIPTION
**Pull request by colossus9**
This is the first iteration of the toolkit, intended to build it out initially and make sure it is functionally sound. There still exists some improvements, such as the top-level README, potential script output formatting (with the planned `-f|--format` option), and additional scripts.

Please provide feedback as necessary.

### CODE REVIEW

**Comment by colossus9** [comment]
@garciavan Looking for your review as well

**Review by garciavan — COMMENTED** [review]
Make sure to finish building out the **README.md** file

**Review by garciavan — APPROVED** [review]
LGTM :+1:

**Comment by colossus9** [comment]
:smiley:

**Pull request merged**
